-- Up Migration

-- Review only: not applied. All future business ownership references accounts.id.
-- UUIDs are generated by trusted backend code with node:crypto randomUUID().
CREATE SCHEMA chawgee;
REVOKE ALL ON SCHEMA chawgee FROM PUBLIC;

CREATE TABLE chawgee.accounts (
  id uuid PRIMARY KEY,
  status text NOT NULL DEFAULT 'active',
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT accounts_status_check CHECK (status IN ('active', 'suspended', 'pending_deletion')),
  CONSTRAINT accounts_timestamp_check CHECK (updated_at >= created_at)
);

CREATE TABLE chawgee.auth_bindings (
  id uuid PRIMARY KEY,
  account_id uuid NOT NULL,
  auth_provider text COLLATE "C" NOT NULL,
  issuer text COLLATE "C" NOT NULL,
  subject text COLLATE "C" NOT NULL,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT auth_bindings_account_fk FOREIGN KEY (account_id)
    REFERENCES chawgee.accounts (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT auth_bindings_identity_unique UNIQUE (issuer, subject),
  CONSTRAINT auth_bindings_provider_check CHECK (
    octet_length(auth_provider) BETWEEN 1 AND 100 AND auth_provider = btrim(auth_provider)
  ),
  CONSTRAINT auth_bindings_issuer_check CHECK (
    octet_length(issuer) BETWEEN 1 AND 512 AND issuer = btrim(issuer)
  ),
  CONSTRAINT auth_bindings_subject_check CHECK (
    octet_length(subject) BETWEEN 1 AND 512 AND subject = btrim(subject)
  ),
  CONSTRAINT auth_bindings_timestamp_check CHECK (updated_at >= created_at)
);

CREATE INDEX auth_bindings_account_id_idx ON chawgee.auth_bindings (account_id);
REVOKE ALL ON TABLE chawgee.accounts, chawgee.auth_bindings FROM PUBLIC;

-- No runtime grants, RLS policies, auth-schema dependencies, or auth users here.
-- Repository writes must maintain updated_at; defaults apply only on insertion.

-- Down Migration

-- Safe rollback only before identities exist. Never silently destroy accounts.
-- The migration runner supplies the transaction; do not run this outside it.
LOCK TABLE chawgee.accounts, chawgee.auth_bindings IN ACCESS EXCLUSIVE MODE;
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM chawgee.accounts)
     OR EXISTS (SELECT 1 FROM chawgee.auth_bindings) THEN
    RAISE EXCEPTION 'Identity rollback refused: account or binding data exists.';
  END IF;
END;
$$;

DROP TABLE chawgee.auth_bindings;
DROP TABLE chawgee.accounts;
DROP SCHEMA chawgee RESTRICT;
